/// Flutter icons IconPack
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconPack
///      fonts:
///       - asset: fonts/IconPack.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconPack {
  IconPack._();

  static const _kFontFam = 'IconPack';

  static const IconData carret_down = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData carret_up = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData carret_foward = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData chart = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData dots_horizontal = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData dots_vertical = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData duplicate = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData effort_icon = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData feedback = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData goal = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData login = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData menu_line = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData send = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData sorting_icon = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData timer = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData carret_backward = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData child = const IconData(0xe83b, fontFamily: _kFontFam);
}
